セクション番号を追加
jaws-ug-cdk/cdk-conf-2024-contribute-workshop pull request #3
Opened 2024-06-13 13:53 UTC by badmintoncryer

環境構築 > コントリビュートの流れ > フォークからビルドまで の順番で表示されるように数字をプレフィックスとして追加

2024-06-13 15:28 UTC, go-to-k requested changes
あ、mdファイル内のリンクも変えて頂けると助かります…！

2024-06-13 22:21 UTC, badmintoncryer commented
@go-to-k おっとすみません！mdxの方も修正しました〜！

2024-06-14 01:26 UTC, go-to-k commented
コントリビュートの流れとルール.mdの中にも1つあったりするのでそちらもお願いします…！

2024-06-14 01:34 UTC, go-to-k commented
github.ioで開いたastroの方だとmdxの方は元々その相対パスだと確か404になってた気がするので直さないといけないのですが…(うろ覚え)

2024-06-14 12:28 UTC, badmintoncryer commented
@go-to-k 2点とも修正しておきました！リンクもローカルで正常動作することを確認済みです〜！

2024-06-14 15:17 UTC, go-to-k commented
お手数おかけしました！完璧です👌
ありがとうございます！！

2024-06-14 15:17 UTC, go-to-k approved these changes

2024-06-14 15:18 UTC, merged