ガイドPR(機能追加)用ドキュメントの作成
jaws-ug-cdk/cdk-conf-2024-contribute-workshop pull request #4
Opened 2024-06-15 00:38 UTC by badmintoncryer

ガイドPRその2の機能追加PR用のドキュメントを作成しました。

お題は色々悩みましたが、SNSのDisplay Name(string)の追加にしました。
非常にシンプルなので、イメージは湧きやすいと思っています。

2024-06-15 15:26 UTC, go-to-k requested changes
すごく丁寧に書いていただきありがとうございます！一応細かめですがコメントしました！

2024-06-15 15:26 UTC, go-to-k commented on src/content/docs/5-機能追加PR(SNS TopicのDisplay Name対応)/display-name.md
> +|Description of changes|変更内容の詳細|Add `displayName` property to `TopicProps` and set it in the `CfnTopic` constructor.|
あ、`Description of how you validated changes`もお願いできたらと！

2024-06-15 15:26 UTC, go-to-k commented on src/content/docs/5-機能追加PR(SNS TopicのDisplay Name対応)/display-name.md
> +自動でCloudformationテンプレートの作成, デプロイ及び削除が行われます。エラーなく完了すれば統合テストも完了です。
一応

```suggestion
自動でCloudformationテンプレートの作成, スタックのデプロイ及び削除が行われます。エラーなく完了すれば統合テストも完了です。
```

2024-06-16 05:28 UTC, badmintoncryer commented on src/content/docs/5-機能追加PR(SNS TopicのDisplay Name対応)/display-name.md
> +  }).toThrowError('displayName must be less than 100 characters');
修正しました！

2024-06-16 10:26 UTC, badmintoncryer commented
@go-to-k ご確認ありがとうございました！！tokenバリデーションなどすっかり抜けていて助かりました！
やや行儀が悪いですが、ついでにリンクも直した？はずです。mainマージ後に治ってるか確認させてください。

2024-06-16 10:43 UTC, go-to-k approved these changes
ありがとうございます！

2024-06-16 10:43 UTC, merged