実践課題用ドキュメントの作成
jaws-ug-cdk/cdk-conf-2024-contribute-workshop pull request #8
Opened 2024-06-22 00:05 UTC by badmintoncryer

実践課題用のドキュメントを作成しました！

お題はECR Repositoryクラスへの`imageTagMutability`引数の追加です。

単純なstringだとつまらないので、enum定義を新要素として追加しています。

2024-06-22 17:24 UTC, go-to-k requested changes
いい感じです！(typoだけコメント)

2024-06-22 17:24 UTC, go-to-k commented on src/content/docs/5-実践課題/tag-mutability.md
> +|Reason for this change|変更理由|We can set a image tag immuutability for an ecr repository from cloudformation, but this was not supported in the AWS CDK L2 construct.|
```suggestion
|Reason for this change|変更理由|We can set an image tag immutability for an ecr repository from cloudformation, but this was not supported in the AWS CDK L2 construct.|
```

2024-06-22 17:24 UTC, go-to-k commented on src/content/docs/5-実践課題/tag-mutability.md
> +  Template.fromStack(stack).hasResourceProperties('AWS::ecr::Repository', {
```suggestion
  Template.fromStack(stack).hasResourceProperties('AWS::ECR::Repository', {
```

2024-06-22 17:24 UTC, go-to-k commented on src/content/docs/5-実践課題/tag-mutability.md
> +  new ecr.repository(stack, 'Myrepository', {
```suggestion
  new ecr.repository(stack, 'MyRepository', {
```

2024-06-22 17:26 UTC, go-to-k approved these changes
マージしちゃいます！

2024-06-22 17:26 UTC, merged

2024-06-23 00:42 UTC, badmintoncryer commented
@go-to-k ご確認ありがとうございました！